# These are supported funding model platforms

github: [stachu540] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: https://paypal.me/stachu540 # Replace with a single custom sponsorship URL