language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install: chmod +x ./gradlew
script: ./gradlew check

jobs:
  include:
  - stage: code coverage
    jdk: openjdk8
    script:
      - ./gradlew codeCoverageReport
      - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    jdk: openjdk8
    script: ./gradlew deploy