# Testing job every Tuesday on 8:00 AM GMT
name: Test Unit - Chron

on: 
  schedule:
    - cron: '0 8 * * 1'

jobs:
  scheduled:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        jvm: [8, 11, 12]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Gradle Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: jdk${{ matrix.jvm }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
        restore-keys: |
          jdk${{ matrix.jvm }}-gradle-
    - name: Set up JDK ${{ matrix.jvm }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jvm }}
    - name: Gradle Test
      run: |
        chmod +x ./gradlew
        ./gradlew test -x javadoc